# -*- coding: utf-8 -*-
"""Students performance program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Th0Tg-re5vmVwJWwepcLiUUmlbHnmjCv

#ADD STUDENT NAMES
"""

students = {}

for i in range (1,6):
  name = input(f"student name: index {i}: ")
  english = int(input("Enter English marks: "))
  math = int(input("Enter Math marks: "))
  science = int(input("Enter Science marks: "))
  students[name] = [english, math, science]

print("All student marks: ")
print(students)

"""#STUDENT GRADES"""

def Grade(total):
    if total >= 270:
        return "A"
    elif total >= 230:
        return "B"
    elif total >= 200:
        return "C"
    elif total >= 150:
        return "D"
    else:
        return "E"

for name, marks in students.items():
  total = sum(marks)
  grade = Grade(total)
  print(f"Student name: {name}, Total marks: {total}, Student grade: {grade}")

"""#SEARCH STUDENTS"""

search_name = input("Enter student name to search: ")

if search_name in students:
    marks = students[search_name]
    print("Marks:", marks)
    print("Total:", sum(marks))
    print("Grade:", Grade(sum(marks)))
else:
    print("Student not found")

search_name = input("Enter student name to search: ")

if search_name in students:
    marks = students[search_name]
    print("Marks:", marks)
    print("Total:", sum(marks))
    print("Grade:", Grade(sum(marks)))
else:
    print("Student not found")

"""#CLASS STATISTICS"""

all_marks = []

for marks in students.values():
    all_marks.extend(marks)

class_average = sum(all_marks) / len(all_marks)
print("Class average:", class_average)

english_scores = []
math_scores = []
science_scores = []

for name, marks in students.items():
    english_scores.append(marks[0])
    math_scores.append(marks[1])
    science_scores.append(marks[2])

Average_english_score = sum(english_scores) / len(english_scores)
Average_math_score = sum(math_scores) / len(math_scores)
Average_science_score = sum(science_scores) / len(science_scores)

print("English average:", Average_english_score)
print("Math average:", Average_math_score)
print("Science average:", Average_science_score)

for name, marks in students.items():
  average = sum(marks) / len(marks)
  print(f"Student name: {name}, Average_score: {average:.2f}")